providers = ["python"]

[phases.setup]
# নির্দিষ্ট একটি ছোট আর্কাইভ বা ডিফল্ট ব্যবহার করা
pkgs = ["python311", "python311Packages.pip", "gcc", "postgresql_16"]

[phases.install]
cmds = [
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r requirements/production.txt"
]

[phases.build]
# এখানে বিল্ড টাইমে সেটিংস বলে দেওয়া ভালো
cmds = [
    "DJANGO_SETTINGS_MODULE=config.settings.production python3 manage.py collectstatic --noinput"
]

[start]
cmd = "daphne -b 0.0.0.0 -p 8000 config.asgi:application"
