# Generated by Django 4.2.11 on 2026-04-01 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_file', models.FileField(upload_to='watch/videos/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='watch/thumbs/%Y/%m/')),
                ('duration', models.FloatField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watch_watchvideo',
                'ordering': ['-created_at'],
            },
        ),
    ]
