# Generated by Django 4.2.11 on 2026-04-03 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_recommendation_engine'),
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchvideo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch_videos', to='posts.contentcategory'),
        ),
        migrations.AddField(
            model_name='watchvideo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='watch_videos', to='posts.contenttag'),
        ),
        migrations.AddIndex(
            model_name='watchvideo',
            index=models.Index(fields=['category', '-created_at'], name='watch_watch_categor_32fd5e_idx'),
        ),
    ]
