# Generated by Django 4.2.11 on 2026-04-03 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0003_recommendation_engine'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('view', 'View'), ('watch', 'Watch'), ('like', 'Like'), ('share', 'Share'), ('click', 'Click')], db_index=True, max_length=16)),
                ('object_id', models.UUIDField()),
                ('watch_seconds', models.FloatField(default=0)),
                ('points_applied', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='posts.contentcategory')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendations_userinteraction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='recommendat_user_id_f1d3d6_idx'), models.Index(fields=['category', '-created_at'], name='recommendat_categor_62e5ae_idx'), models.Index(fields=['action', '-created_at'], name='recommendat_action_de5bac_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserCategoryScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='posts.contentcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendations_usercategoryscore',
                'indexes': [models.Index(fields=['user', '-score'], name='recommendat_user_id_868959_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='usercategoryscore',
            constraint=models.UniqueConstraint(fields=('user', 'category'), name='unique_user_category_score'),
        ),
    ]
