# Generated by Django 4.2.11 on 2026-04-01 02:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('media', models.ImageField(blank=True, null=True, upload_to='comments/%Y/%m/')),
                ('reactions_count', models.JSONField(blank=True, default=dict)),
                ('replies_count', models.PositiveIntegerField(default=0)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'comments_comment',
                'ordering': ['created_at'],
            },
        ),
    ]
