# Generated by Django 4.2.11 on 2026-04-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interest_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
