# Generated by Django 4.2.11 on 2026-04-01 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='callparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='call',
            name='caller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='call',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='call',
            name='participants',
            field=models.ManyToManyField(related_name='calls', through='calls.CallParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='callparticipant',
            constraint=models.UniqueConstraint(fields=('call', 'user'), name='unique_call_participant'),
        ),
    ]
