# Generated by Django 4.2.11 on 2026-04-01 02:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='pages/avatars/%Y/%m/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='pages/covers/%Y/%m/')),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('verified', models.BooleanField(default=False)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pages_page',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('editor', 'Editor'), ('analyst', 'Analyst')], default='editor', max_length=20)),
            ],
            options={
                'db_table': 'pages_pageadmin',
            },
        ),
        migrations.CreateModel(
            name='PageFollower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_liked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_rel', to='pages.page')),
            ],
            options={
                'db_table': 'pages_pagefollower',
            },
        ),
    ]
