# Generated by Django 4.2.11 on 2026-04-01 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recentsearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedsnooze',
            name='snoozed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snoozed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedsnooze',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_snoozes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedhide',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AddField(
            model_name='feedhide',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_hides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='savedpost',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_saved_post'),
        ),
        migrations.AddConstraint(
            model_name='feedsnooze',
            constraint=models.UniqueConstraint(fields=('user', 'snoozed_user'), name='unique_snooze_pair'),
        ),
        migrations.AddConstraint(
            model_name='feedhide',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_feed_hide'),
        ),
    ]
