# Generated by Django 4.2.11 on 2026-04-01 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSuspension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_permanent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('lifted', 'Lifted'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_suspensions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_suspensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suspensions_account',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='suspensions_user_id_e0bc1e_idx'), models.Index(fields=['ends_at'], name='suspensions_ends_at_694809_idx')],
            },
        ),
    ]
