# Generated by Django 4.2.11 on 2026-04-01 02:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('post_type', models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('video', 'Video'), ('link', 'Link'), ('feeling', 'Feeling'), ('checkin', 'Checkin'), ('shared', 'Shared')], default='text', max_length=20)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('only_me', 'Only me'), ('custom', 'Custom')], default='public', max_length=20)),
                ('feeling', models.CharField(blank=True, max_length=120, null=True)),
                ('location', models.JSONField(blank=True, null=True)),
                ('link_preview', models.JSONField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('reactions_count', models.JSONField(blank=True, default=dict)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'posts_post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='posts/media/%Y/%m/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('gif', 'Gif')], default='image', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='posts/thumbs/%Y/%m/')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'posts_postmedia',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'posts_postview',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media', models.FileField(blank=True, null=True, upload_to='stories/%Y/%m/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text')], default='image', max_length=20)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('background_color', models.CharField(blank=True, max_length=32, null=True)),
                ('stickers', models.JSONField(blank=True, null=True)),
                ('music', models.JSONField(blank=True, null=True)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('close_friends', 'Close friends')], default='friends', max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'posts_story',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='posts.story')),
            ],
            options={
                'db_table': 'posts_storyview',
            },
        ),
    ]
