# Generated by Django 4.2.11 on 2026-04-01 02:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=512, unique=True)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notifications_fcmdevice',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('friend_request', 'Friend request'), ('friend_accept', 'Friend accept'), ('post_like', 'Post like'), ('post_comment', 'Post comment'), ('comment_reply', 'Comment reply'), ('post_share', 'Post share'), ('tag', 'Tag'), ('mention', 'Mention'), ('group_invite', 'Group invite'), ('group_post', 'Group post'), ('page_post', 'Page post'), ('birthday', 'Birthday'), ('memory', 'Memory'), ('call_missed', 'Call missed'), ('message', 'Message'), ('live_started', 'Live started'), ('event_reminder', 'Event reminder')], max_length=40)),
                ('verb', models.CharField(max_length=255)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('push_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_friend_requests', models.BooleanField(default=True)),
                ('email_messages', models.BooleanField(default=True)),
                ('email_posts', models.BooleanField(default=True)),
                ('push_friend_requests', models.BooleanField(default=True)),
                ('push_messages', models.BooleanField(default=True)),
                ('push_posts', models.BooleanField(default=True)),
                ('push_calls', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'notifications_notificationsettings',
            },
        ),
    ]
